name: Aggiorna EPG
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Esegui Script
        run: python filter.py

      - name: Verifica ed Invia
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Verifica se il file esiste prima di aggiungerlo
          if [ -f epg.xml ]; then
            git add epg.xml
            git commit -m "Aggiornamento automatico EPG" || exit 0
            git push
          else
            echo "Errore: epg.xml non è stato creato!"
            exit 1
          fi
